server:
  port: 8081

spring:
  application:
    name: product-api
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5